# Generated by Django 5.2.6 on 2026-03-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sede_user_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='imagen_referencia',
            field=models.ImageField(blank=True, null=True, upload_to='sedes/'),
        ),
    ]
