# Generated by Django 5.2.6 on 2026-03-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sede_imagen_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='sede',
            name='foto_pastor',
            field=models.ImageField(blank=True, null=True, upload_to='pastores/'),
        ),
    ]
