# Generated by Django 5.2.6 on 2026-03-24 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sede_ciudad_sede_foto_pastor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastorSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pastores/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastores_adicionales', to='core.sede')),
            ],
            options={
                'verbose_name': 'Pastor de sede',
                'verbose_name_plural': 'Pastores de sede',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
