# Generated by Django 5.2.6 on 2026-03-24 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pastorsede'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pastorsede',
            options={'ordering': ['nombre'], 'verbose_name': 'Pastor de sede', 'verbose_name_plural': 'Pastores de sede'},
        ),
        migrations.RemoveField(
            model_name='pastorsede',
            name='orden',
        ),
    ]
