# Generated by Django 5.2.6 on 2026-03-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_pastorsede_options_remove_pastorsede_orden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sede',
            options={'ordering': ['departamento', 'ciudad', 'nombre'], 'verbose_name': 'Sede', 'verbose_name_plural': 'Sedes'},
        ),
        migrations.AddField(
            model_name='sede',
            name='departamento',
            field=models.CharField(blank=True, default='', help_text='ID del departamento (Colombia), desde el formulario de sede.', max_length=10),
        ),
        migrations.AlterField(
            model_name='sede',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='sede',
            constraint=models.UniqueConstraint(fields=('nombre', 'departamento', 'ciudad'), name='core_sede_unique_nombre_ubicacion'),
        ),
    ]
