# Generated by Django 5.2.6 on 2026-03-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sede_departamento_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='direccion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
