# Generated by Django 5.2.6 on 2026-04-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sede_direccion_opcional'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='direccion',
            field=models.TextField(blank=True, default='', verbose_name='Dirección'),
        ),
    ]
