# Generated by Django 5.2.6 on 2026-04-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_email_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='documento_identidad',
            field=models.CharField(blank=True, help_text='Cédula u otro documento; debe ser único en el sistema.', max_length=32, null=True, unique=True, verbose_name='Número de identificación'),
        ),
    ]
