# Generated by Django 5.2.6 on 2026-04-17 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_documento_identidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('CE', 'Cédula de extranjería'), ('PAS', 'Pasaporte')], default='CC', max_length=3, null=True, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='documento_identidad',
            field=models.CharField(blank=True, help_text='Número del documento; debe ser único en el sistema.', max_length=32, null=True, unique=True, verbose_name='Número de identificación'),
        ),
    ]
