# Generated by Django 5.2.6 on 2026-07-26 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rellena_departamento_pasto_sin_dep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sede',
            name='foto_pastor',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='pastor_responsable',
        ),
        migrations.DeleteModel(
            name='PastorSede',
        ),
    ]
