# Generated by Django 5.2.6 on 2026-07-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_limpia_contenttypes_huerfanos'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='barrio',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Barrio'),
        ),
        migrations.AddField(
            model_name='user',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Ciudad o municipio'),
        ),
        migrations.AddField(
            model_name='user',
            name='departamento',
            field=models.CharField(blank=True, default='', help_text='Código del departamento (Colombia).', max_length=10, verbose_name='Departamento'),
        ),
    ]
