# Generated by Django 5.2.6 on 2025-09-19 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_sede_user_sede'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministerio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministerios_responsable', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ministerios', to='core.sede')),
            ],
            options={
                'verbose_name': 'Ministerio',
                'verbose_name_plural': 'Ministerios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PersonaNueva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('direccion', models.TextField(blank=True)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('visitante', 'Visitante'), ('interesado', 'Interesado'), ('miembro', 'Miembro'), ('inactivo', 'Inactivo')], default='nuevo', max_length=20)),
                ('fecha_primera_visita', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('como_conocio', models.CharField(blank=True, help_text='¿Cómo conoció la iglesia?', max_length=200)),
                ('intereses', models.TextField(blank=True, help_text='Intereses espirituales o ministerios')),
                ('necesidades_especiales', models.TextField(blank=True, help_text='Necesidades especiales o solicitudes')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales')),
                ('referido_por', models.CharField(blank=True, help_text='Persona que lo refirió', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsable_seguimiento', models.ForeignKey(blank=True, help_text='Persona responsable del seguimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas_seguimiento', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personas_nuevas', to='core.sede')),
            ],
            options={
                'verbose_name': 'Persona Nueva',
                'verbose_name_plural': 'Personas Nuevas',
                'ordering': ['-fecha_registro', 'nombre', 'apellido'],
            },
        ),
        migrations.CreateModel(
            name='EventoEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('bautismo', 'Bautismo'), ('clase_nuevos', 'Clase de Nuevos Miembros'), ('retiro', 'Retiro'), ('conferencia', 'Conferencia'), ('servicio_especial', 'Servicio Especial'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_evento', models.DateTimeField()),
                ('lugar', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_responsable', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_especiales', to='core.sede')),
                ('personas_confirmadas', models.ManyToManyField(blank=True, related_name='eventos_confirmado', to='guias.personanueva')),
                ('personas_invitadas', models.ManyToManyField(blank=True, related_name='eventos_invitado', to='guias.personanueva')),
            ],
            options={
                'verbose_name': 'Evento Especial',
                'verbose_name_plural': 'Eventos Especiales',
                'ordering': ['-fecha_evento'],
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('llamada', 'Llamada telefónica'), ('visita', 'Visita personal'), ('email', 'Correo electrónico'), ('mensaje', 'Mensaje de texto'), ('reunion', 'Reunión'), ('evento', 'Evento especial'), ('otro', 'Otro')], max_length=20)),
                ('fecha_seguimiento', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('resultado', models.TextField(blank=True, help_text='Resultado del seguimiento')),
                ('proxima_accion', models.TextField(blank=True, help_text='Próxima acción a realizar')),
                ('fecha_proxima_accion', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='guias.personanueva')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
                'ordering': ['-fecha_seguimiento'],
            },
        ),
        migrations.CreateModel(
            name='InteresMinisterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_interes', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='medio', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('fecha_interes', models.DateTimeField(auto_now_add=True)),
                ('ministerio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas_interesadas', to='guias.ministerio')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intereses_ministerio', to='guias.personanueva')),
            ],
            options={
                'verbose_name': 'Interés en Ministerio',
                'verbose_name_plural': 'Intereses en Ministerios',
                'ordering': ['-fecha_interes'],
                'unique_together': {('persona', 'ministerio')},
            },
        ),
    ]
