"""
Django settings for hechoshub project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from .db_config import get_database_config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_env_file(env_path: Path) -> None:
    if not env_path.exists():
        return

    for raw_line in env_path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue

        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key, value)


_load_env_file(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-fyeln-_#5#e)7_xwm97phwv2bg-@bqn06nwo1od2vht-t7+2)7')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'true').lower() in {'1', 'true', 'yes', 'on'}

ALLOWED_HOSTS = [host.strip() for host in os.getenv('DJANGO_ALLOWED_HOSTS', '').split(',') if host.strip()]
_render_host = os.getenv('RENDER_EXTERNAL_HOSTNAME', '').strip()
if _render_host and _render_host not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_render_host)

CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.getenv('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',')
    if o.strip()
]
if _render_host:
    _origin = f'https://{_render_host}'
    if _origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_origin)

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = os.getenv('DJANGO_SECURE_SSL_REDIRECT', 'true').lower() in {'1', 'true', 'yes', 'on'}
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    
    # Third party apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
    
    # Local apps
    'core',
    'hechos',
    'ofrendas',
    'guias',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'hechoshub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.sede_actual',
                'hechos.context_processors.profesor_entregas_pendientes',
            ],
        },
    },
]

WSGI_APPLICATION = 'hechoshub.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': get_database_config(BASE_DIR)
}

# Pooler PgBouncer (Supabase 6543, Neon *-pooler.*): sin cursores del lado del servidor.
_default_db = DATABASES['default']
_db_host = str(_default_db.get('HOST') or '')
_db_port = str(_default_db.get('PORT') or '')
_use_pooler_fix = (
    _db_port == '6543'
    and ('supabase.co' in _db_host or 'pooler.supabase.com' in _db_host)
) or ('neon.tech' in _db_host and '-pooler' in _db_host)
if _use_pooler_fix:
    _default_db['CONN_MAX_AGE'] = 0
    _default_db['DISABLE_SERVER_SIDE_CURSORS'] = True


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 6},
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Estáticos en producción: collectstatic al build + WhiteNoise (middleware arriba). No hace falta STORAGES custom.

# Debe empezar con / para que {{ archivo.url }} apunte al sitio raíz, no bajo /hechos/...
MEDIA_URL = '/media/'
# Entregas de actividades: escuelasBiblicas/media/actividades/<año>/<mes>/ (ver FileField upload_to)
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication settings
AUTHENTICATION_BACKENDS = [
    'core.auth_backends.EmailOrDocumentBackend',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

# Allauth settings
ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_SIGNUP_FIELDS = ['username*', 'password1*', 'password2*', 'email']
ACCOUNT_EMAIL_VERIFICATION = 'none'  # Deshabilitado para desarrollo
ACCOUNT_RATE_LIMITS = {
    'login_failed': '5/5m/key,10/m/ip',
}
ACCOUNT_ADAPTER = 'core.adapters.StudentAccountAdapter'
ACCOUNT_FORMS = {
    'signup': 'core.forms.StudentSignupForm',
}

# Email settings para desarrollo
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Social authentication settings
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    },
    'github': {
        'SCOPE': [
            'user',
            'email',
        ],
    }
}

# Login/Logout URLs
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/inicio/'
ACCOUNT_LOGOUT_ON_GET = True

# Custom user model
AUTH_USER_MODEL = 'core.User'

# Subidas (importación Excel en director, medios, etc.)
# Por defecto 15 MiB; en Render/hosting ajustar vía DATA_UPLOAD_MAX_MEMORY_BYTES si hace falta.
_data_upload_max = int(os.getenv('DATA_UPLOAD_MAX_MEMORY_BYTES', str(15 * 1024 * 1024)))
DATA_UPLOAD_MAX_MEMORY_SIZE = _data_upload_max
FILE_UPLOAD_MAX_MEMORY_SIZE = _data_upload_max
