# Generated by Django 5.2.6 on 2025-09-18 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sede_user_sede'),
        ('hechos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminescuela',
            name='escuela',
        ),
        migrations.AddField(
            model_name='adminescuela',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins_escuela', to='core.sede'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='core.sede'),
        ),
        migrations.AddField(
            model_name='clase',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='core.sede'),
        ),
        migrations.AddField(
            model_name='curso',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='core.sede'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='core.sede'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='core.sede'),
        ),
        migrations.AddField(
            model_name='nota',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='core.sede'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesores', to='core.sede'),
        ),
        migrations.AddField(
            model_name='rutaestudio',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rutas_estudio', to='core.sede'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='codigo_estudiante',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='codigo_profesor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
