# Generated by Django 5.2.6 on 2025-09-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hechos', '0002_remove_adminescuela_escuela_adminescuela_sede_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['ruta_estudio', 'orden', 'fecha_inicio'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AddField(
            model_name='curso',
            name='orden',
            field=models.PositiveIntegerField(default=1, help_text='Orden en la secuencia de la ruta de estudio'),
        ),
    ]
