# Generated by Django 5.2.6 on 2025-09-18 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hechos', '0003_alter_curso_options_curso_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='capacidad_maxima',
        ),
    ]
