# Generated by Django 5.2.6 on 2025-09-18 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hechos', '0004_remove_curso_capacidad_maxima'),
    ]

    operations = [
    ]
