# Generated by Django 5.2.6 on 2025-09-18 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hechos', '0005_auto_20250918_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clase',
            options={'ordering': ['edicion_curso', 'numero_clase'], 'verbose_name': 'Clase', 'verbose_name_plural': 'Clases'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['ruta_estudio', 'orden', 'nombre'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.RemoveField(
            model_name='curso',
            name='aula',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='profesor',
        ),
        migrations.AddField(
            model_name='curso',
            name='duracion_semanas',
            field=models.PositiveIntegerField(default=4, help_text='Duración en semanas'),
        ),
        migrations.CreateModel(
            name='EdicionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_edicion', models.CharField(help_text='Ej: Grupo A, Matutino, Vespertino', max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('horario', models.CharField(help_text='Ej: Lunes y Miércoles 7:00 PM', max_length=100)),
                ('aula', models.CharField(blank=True, max_length=50)),
                ('cupo_maximo', models.PositiveIntegerField(default=30, help_text='Cupo máximo de estudiantes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ediciones', to='hechos.curso')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ediciones_curso', to='hechos.profesor')),
            ],
            options={
                'verbose_name': 'Edición de Curso',
                'verbose_name_plural': 'Ediciones de Curso',
                'ordering': ['curso', 'fecha_inicio'],
                'unique_together': {('curso', 'nombre_edicion')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='clase',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='clase',
            name='edicion_curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='hechos.edicioncurso'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='edicion_curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='hechos.edicioncurso'),
        ),
        migrations.AlterUniqueTogether(
            name='clase',
            unique_together={('edicion_curso', 'numero_clase')},
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('estudiante', 'edicion_curso')},
        ),
        migrations.RemoveField(
            model_name='clase',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='curso',
        ),
    ]
