# Generated by Django 5.2.6 on 2025-09-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hechos', '0006_alter_clase_options_alter_curso_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='periodo',
            field=models.CharField(default='2025-1', help_text='Período académico (ej: 2025-1, 2025-2)', max_length=20),
        ),
    ]
