# Generated by Django 5.2.6 on 2025-09-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hechos', '0007_matricula_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='puntaje_maximo',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
