# Generated by Django 5.2.6 on 2026-03-21 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sede_user_sede'),
        ('hechos', '0008_update_nota_puntaje_maximo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('pago_validado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edicion_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_matricula', to='hechos.edicioncurso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_matricula', to='hechos.estudiante')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_matricula_revisadas', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_matricula', to='core.sede')),
            ],
            options={
                'verbose_name': 'Solicitud de Matrícula',
                'verbose_name_plural': 'Solicitudes de Matrícula',
                'ordering': ['-fecha_solicitud'],
                'unique_together': {('estudiante', 'edicion_curso')},
            },
        ),
    ]
