# Generated by Django 5.2.6 on 2026-03-21 19:53

import django.db.models.deletion
from django.db import migrations, models


def backfill_escuelas_desde_rutas(apps, schema_editor):
    Escuela = apps.get_model('hechos', 'Escuela')
    RutaEstudio = apps.get_model('hechos', 'RutaEstudio')

    for ruta in RutaEstudio.objects.filter(escuela__isnull=True):
        escuela, _ = Escuela.objects.get_or_create(
            sede=ruta.sede,
            nombre=f"Escuela {ruta.nombre}",
            defaults={
                'descripcion': f"Escuela generada automáticamente desde {ruta.nombre}.",
                'is_active': True,
            },
        )
        ruta.escuela = escuela
        ruta.save(update_fields=['escuela'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sede_user_sede'),
        ('hechos', '0009_solicitudmatricula'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rutaestudio',
            options={'ordering': ['escuela__nombre', 'nivel', 'nombre'], 'verbose_name': 'Nivel', 'verbose_name_plural': 'Niveles'},
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escuelas', to='core.sede')),
            ],
            options={
                'verbose_name': 'Escuela',
                'verbose_name_plural': 'Escuelas',
                'ordering': ['nombre'],
                'unique_together': {('sede', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='rutaestudio',
            name='escuela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='niveles', to='hechos.escuela'),
        ),
        migrations.RunPython(backfill_escuelas_desde_rutas, migrations.RunPython.noop),
    ]
