# Generated by Django 5.2.6 on 2026-03-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hechos', '0010_alter_rutaestudio_options_escuela_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminescuela',
            name='tipo_coordinador',
            field=models.CharField(choices=[('sede', 'Coordinador de sede'), ('academico', 'Coordinador académico'), ('pedagogico', 'Coordinador pedagógico'), ('financiero', 'Coordinador financiero'), ('logistico', 'Coordinador logístico')], default='academico', max_length=20),
        ),
        migrations.AlterField(
            model_name='adminescuela',
            name='cargo',
            field=models.CharField(max_length=200),
        ),
    ]
