# Generated by Django 5.2.6 on 2026-03-26 02:47

import hechos.models
from django.db import migrations, models


def _drop_escuela_unique_constraints(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor != "postgresql":
        return
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT c.conname
            FROM pg_constraint c
            JOIN pg_class t ON c.conrelid = t.oid
            WHERE t.relname = 'hechos_escuela' AND c.contype = 'u'
            """
        )
        qn = connection.ops.quote_name
        for (name,) in cursor.fetchall():
            cursor.execute(
                f'ALTER TABLE {qn("hechos_escuela")} DROP CONSTRAINT IF EXISTS {qn(name)}'
            )


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("hechos", "0013_escuela_maestro"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="escuela",
            options={
                "ordering": ["-anio", "ciclo", "grupo", "nombre"],
                "verbose_name": "Escuela",
                "verbose_name_plural": "Escuelas",
            },
        ),
        migrations.RunPython(_drop_escuela_unique_constraints, _noop),
        migrations.AddField(
            model_name="escuela",
            name="anio",
            field=models.PositiveIntegerField(
                default=hechos.models.default_anio_escuela,
                help_text="Año de referencia (por defecto el año en curso).",
                verbose_name="Año",
            ),
        ),
        migrations.AddField(
            model_name="escuela",
            name="ciclo",
            field=models.CharField(
                choices=[("A", "Ciclo A"), ("B", "Ciclo B")],
                default="A",
                max_length=1,
                verbose_name="Ciclo",
            ),
        ),
        migrations.AddField(
            model_name="escuela",
            name="grupo",
            field=models.PositiveIntegerField(default=1, verbose_name="Grupo"),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name="escuela",
                    unique_together={("sede", "nombre", "anio", "ciclo", "grupo")},
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=r"""
                    DO $$ BEGIN
                        ALTER TABLE hechos_escuela
                        ADD CONSTRAINT hechos_escuela_sede_nombre_anio_ciclo_grupo_uniq
                            UNIQUE (sede_id, nombre, anio, ciclo, grupo);
                    EXCEPTION
                        WHEN duplicate_object THEN NULL;
                    END $$;
                    """,
                    reverse_sql="""
                    ALTER TABLE hechos_escuela
                    DROP CONSTRAINT IF EXISTS hechos_escuela_sede_nombre_anio_ciclo_grupo_uniq;
                    """,
                ),
            ],
        ),
    ]
