# Generated by Django 5.2.6 on 2026-03-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hechos", "0014_escuela_anio_ciclo_grupo"),
    ]

    operations = [
        migrations.AddField(
            model_name="estudiante",
            name="numero_documento",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="estudiante",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("CC", "Cedula de ciudadania"),
                    ("TI", "Tarjeta de identidad"),
                    ("CE", "Cedula de extranjeria"),
                    ("PAS", "Pasaporte"),
                ],
                default="CC",
                max_length=3,
            ),
        ),
    ]
