# Generated by Django 5.2.6 on 2026-03-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hechos', '0015_estudiante_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='es_viajero',
            field=models.BooleanField(default=False, help_text='Visitante que vive en otra ciudad y asiste por única vez.'),
        ),
    ]
