# Generated by Django 5.2.6 on 2026-03-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hechos', '0016_estudiante_es_viajero'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='es_reconciliado',
            field=models.BooleanField(default=False, help_text='Asistía antes a una iglesia cristiana y regresa.'),
        ),
    ]
