# Generated by Django 5.2.6 on 2026-03-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hechos', '0017_estudiante_es_reconciliado'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='peticion_area',
            field=models.CharField(blank=True, choices=[('salud', 'Salud'), ('familiar', 'Familiar'), ('financiera', 'Financiera'), ('educacion', 'Educación'), ('laboral', 'Laboral'), ('otro', 'Otro')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='peticion_otro',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='peticion_texto',
            field=models.TextField(blank=True, default=''),
        ),
    ]
