# Generated by Django 5.2.6 on 2026-03-27 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hechos', '0018_estudiante_peticion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='peticion_otro',
        ),
    ]
