# Generated by Django 5.2.6 on 2026-03-27 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hechos', '0019_remove_peticion_otro'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('aprobacion', 'Aprobación'), ('rechazo', 'Rechazo'), ('info', 'Información')], default='info', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField(blank=True)),
                ('leida', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='hechos.estudiante')),
            ],
            options={
                'verbose_name': 'Notificación de estudiante',
                'verbose_name_plural': 'Notificaciones de estudiante',
                'ordering': ['-created_at'],
            },
        ),
    ]
