# Generated by Django 5.2.6 on 2026-03-27 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_pastorsede_options_remove_pastorsede_orden'),
        ('hechos', '0020_notificacion_estudiante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudEspecialEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('salud', 'Salud'), ('familiar', 'Familiar'), ('economica', 'Económica'), ('academica', 'Académica'), ('otra', 'Otra')], default='otra', max_length=20)),
                ('asunto', models.CharField(max_length=180)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('atendida', 'Atendida'), ('cerrada', 'Cerrada')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_especiales', to='hechos.estudiante')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_especiales_revisadas', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_especiales', to='core.sede')),
            ],
            options={
                'verbose_name': 'Solicitud especial',
                'verbose_name_plural': 'Solicitudes especiales',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
