# Generated by Django 5.2.6 on 2026-03-27 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hechos', '0021_solicitudes_especiales_estudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='es_reconciliado',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='es_viajero',
        ),
    ]
