# Generated by Django 5.2.6 on 2026-03-31 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hechos', '0022_remove_viajero_reconciliado'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='estado_civil',
            field=models.CharField(choices=[('no_especificado', 'No especificado'), ('soltero', 'Soltero(a)'), ('casado', 'Casado(a)'), ('union_libre', 'Unión libre'), ('divorciado', 'Divorciado(a)'), ('viudo', 'Viudo(a)'), ('separado', 'Separado(a)'), ('otro', 'Otro')], default='no_especificado', max_length=20),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='genero',
            field=models.CharField(choices=[('no_especificado', 'No especificado'), ('femenino', 'Femenino'), ('masculino', 'Masculino'), ('otro', 'Otro')], default='no_especificado', max_length=20),
        ),
    ]
