# Generated by Django 5.2.6 on 2026-03-31 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sede_direccion_opcional'),
        ('hechos', '0023_estudiante_estado_civil_estudiante_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuejaReclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('queja', 'Queja'), ('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia')], default='queja', max_length=20)),
                ('asunto', models.CharField(max_length=180)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('recibida', 'Recibida'), ('en_proceso', 'En proceso'), ('cerrada', 'Cerrada')], default='recibida', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asignado_a', models.ForeignKey(blank=True, help_text='Coordinador pedagógico asignado en el momento de envío.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quejas_reclamos_asignadas', to='hechos.adminescuela')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quejas_reclamos', to='hechos.estudiante')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quejas_reclamos', to='core.sede')),
            ],
            options={
                'verbose_name': 'Queja/Reclamo',
                'verbose_name_plural': 'Quejas y reclamos',
                'ordering': ['-created_at'],
            },
        ),
    ]
