# Generated by Django 5.2.6 on 2026-03-31 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hechos', '0024_quejareclamo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdicionCursoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estructura_horarios', to='hechos.edicioncurso')),
            ],
            options={
                'verbose_name': 'Horario de edición',
                'verbose_name_plural': 'Horarios de edición',
                'ordering': ['edicion', 'dia_semana', 'hora'],
                'constraints': [models.UniqueConstraint(fields=('edicion', 'dia_semana'), name='uniq_edicion_dia_semana')],
            },
        ),
    ]
