# Generated by Django 5.2.6 on 2026-04-01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("hechos", "0025_edicioncursohorario"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ofrenda",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fecha", models.DateField(default=timezone.now)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                ("descripcion", models.CharField(blank=True, default="", max_length=220)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "escuela",
                    models.ForeignKey(
                        help_text="Escuela a la que corresponde la ofrenda.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ofrendas",
                        to="hechos.escuela",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ofrendas_registradas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ofrendas_hechos",
                        to="core.sede",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ofrenda",
                "verbose_name_plural": "Ofrendas",
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="ofrenda",
            index=models.Index(fields=["sede", "escuela", "fecha"], name="hechos_ofre_sede_id_0dc687_idx"),
        ),
    ]

