# Generated by Django 5.2.6 on 2026-04-05 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hechos', '0026_ofrenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quejareclamo',
            name='asignado_a',
            field=models.ForeignKey(blank=True, help_text='Coordinador académico asignado en el momento de envío.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quejas_reclamos_asignadas', to='hechos.adminescuela'),
        ),
    ]
