# Generated by Django 5.2.6 on 2026-04-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hechos', '0027_alter_quejareclamo_asignado_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quejareclamo',
            name='tipo',
            field=models.CharField(choices=[('queja', 'Queja'), ('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia'), ('solicitud', 'Solicitud especial')], default='queja', max_length=20),
        ),
    ]
