# Generated by Django 5.2.6 on 2026-04-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hechos', '0028_quejareclamo_tipo_solicitud'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudespecialestudiante',
            options={'ordering': ['-fecha_solicitud'], 'verbose_name': 'Solicitud', 'verbose_name_plural': 'Solicitudes'},
        ),
        migrations.AlterField(
            model_name='quejareclamo',
            name='tipo',
            field=models.CharField(choices=[('queja', 'Queja'), ('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia'), ('solicitud', 'Solicitud')], default='queja', max_length=20),
        ),
    ]
