# Generated by Django 5.2.6 on 2026-04-06 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_direccion'),
        ('hechos', '0029_solicitud_semantica_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('codigo', models.CharField(blank=True, help_text='Opcional (ej. A-101).', max_length=50, verbose_name='Código')),
                ('capacidad_plazas', models.PositiveIntegerField(help_text='Número máximo de personas o asientos.', verbose_name='Capacidad (plazas)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salones', to='core.sede')),
            ],
            options={
                'verbose_name': 'Salón',
                'verbose_name_plural': 'Salones',
                'ordering': ['sede', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('sede', 'nombre'), name='uniq_hechos_salon_nombre_por_sede')],
            },
        ),
    ]
