# Generated by Django 5.2.6 on 2026-04-06 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hechos', '0030_salon'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='escuela',
            field=models.ForeignKey(blank=True, help_text='Escuela de la misma sede que usa este salón (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salones_asignados', to='hechos.escuela', verbose_name='Escuela asignada'),
        ),
    ]
