# Generated by Django 5.2.6 on 2026-04-06 04:08

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Count


def dedupe_salon_por_escuela(apps, schema_editor):
    Salon = apps.get_model('hechos', 'Salon')
    for row in (
        Salon.objects.exclude(escuela_id__isnull=True)
        .values('escuela_id')
        .annotate(n=Count('id'))
        .filter(n__gt=1)
    ):
        eid = row['escuela_id']
        pks = list(
            Salon.objects.filter(escuela_id=eid).order_by('id').values_list('id', flat=True)
        )
        for pk in pks[1:]:
            Salon.objects.filter(pk=pk).update(escuela_id=None)


def dedupe_salon_por_escuela_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_direccion'),
        ('hechos', '0031_salon_escuela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='escuela',
            field=models.ForeignKey(blank=True, help_text='Como máximo un salón por escuela; escuela de la misma sede (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salones_asignados', to='hechos.escuela', verbose_name='Escuela asignada'),
        ),
        migrations.RunPython(dedupe_salon_por_escuela, dedupe_salon_por_escuela_reverse),
        migrations.AddConstraint(
            model_name='salon',
            constraint=models.UniqueConstraint(condition=models.Q(('escuela__isnull', False)), fields=('escuela',), name='uniq_hechos_un_salon_por_escuela'),
        ),
    ]
