# Generated by Django 5.2.6 on 2026-04-06 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_direccion'),
        ('hechos', '0032_salon_un_solo_por_escuela'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del evento o del gasto previsto (ej. retiro, materiales, refrigerio).', max_length=200)),
                ('fecha_evento', models.DateField(blank=True, help_text='Opcional. Fecha prevista en que ocurre o se liquida el gasto.', null=True, verbose_name='Fecha del evento')),
                ('monto_destinado', models.DecimalField(decimal_places=2, help_text='Cuánto dinero de la sede planeas usar para este evento o partida.', max_digits=14, verbose_name='Monto a destinar')),
                ('notas', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos_evento_creados', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos_evento', to='core.sede')),
            ],
            options={
                'verbose_name': 'Presupuesto de evento',
                'verbose_name_plural': 'Presupuestos de eventos',
                'ordering': ['-fecha_evento', '-created_at', '-id'],
            },
        ),
    ]
