# Generated by Django 5.2.6 on 2026-04-06 05:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_direccion'),
        ('hechos', '0033_presupuesto_evento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecaudoOcasional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Valor del ingreso recaudado.', max_digits=14, verbose_name='Monto')),
                ('concepto', models.CharField(help_text='En pocas palabras: qué es este dinero (ej. sobrante retiro, donación puntual).', max_length=200, verbose_name='Concepto')),
                ('detalle', models.TextField(blank=True, default='', verbose_name='Detalle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recaudos_ocasionales_registrados', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recaudos_ocasionales', to='core.sede')),
            ],
            options={
                'verbose_name': 'Recaudo ocasional',
                'verbose_name_plural': 'Recaudos ocasionales',
                'ordering': ['-fecha', '-created_at', '-id'],
                'indexes': [models.Index(fields=['sede', 'fecha'], name='hechos_recaud_sede_fecha_idx')],
            },
        ),
    ]
