# Generated by Django 5.2.6 on 2026-04-06 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_direccion'),
        ('hechos', '0034_recaudo_ocasional'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadEscuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tarea', 'Tarea o trabajo escrito'), ('entrega_archivo', 'Entrega de archivo'), ('cuestionario', 'Cuestionario breve'), ('foro', 'Foro o discusión'), ('lectura', 'Lectura / material de estudio'), ('otro', 'Otro')], default='tarea', max_length=32)),
                ('titulo', models.CharField(max_length=220)),
                ('instrucciones', models.TextField(blank=True)),
                ('fecha_limite', models.DateTimeField(blank=True, help_text='Opcional. Hasta cuándo deben entregar o completar el trabajo.', null=True, verbose_name='Fecha límite')),
                ('puntos_posibles', models.DecimalField(blank=True, decimal_places=2, help_text='Opcional, si calificas esta actividad.', max_digits=6, null=True, verbose_name='Puntos posibles')),
                ('material_adjunto', models.FileField(blank=True, help_text='PDF u otro archivo para los estudiantes (opcional).', null=True, upload_to='actividades_escuela/%Y/%m/', verbose_name='Material de apoyo')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_publicadas', to='hechos.profesor')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='hechos.escuela')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_escuela', to='core.sede')),
            ],
            options={
                'verbose_name': 'Actividad de escuela',
                'verbose_name_plural': 'Actividades de escuela',
                'ordering': ['-created_at'],
            },
        ),
    ]
