# Generated by Django 5.2.6 on 2026-04-06 21:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_direccion'),
        ('hechos', '0035_actividad_escuela'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, help_text='Escribe aquí tu trabajo o explicación.', verbose_name='Respuesta o comentario')),
                ('archivo', models.FileField(blank=True, help_text='PDF, Word u otro formato permitido (opcional si ya escribiste respuesta).', null=True, upload_to='entregas_actividades/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'doc', 'docx', 'odt', 'txt', 'rtf', 'png', 'jpg', 'jpeg', 'webp'))], verbose_name='Archivo de evidencia')),
                ('enviado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('puntaje_asignado', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Puntaje')),
                ('comentario_docente', models.TextField(blank=True, verbose_name='Retroalimentación del docente')),
                ('evaluado_en', models.DateTimeField(blank=True, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='hechos.actividadescuela')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_actividades', to='hechos.estudiante')),
                ('evaluado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_evaluadas', to='hechos.profesor')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_actividad', to='core.sede')),
            ],
            options={
                'verbose_name': 'Entrega de actividad',
                'verbose_name_plural': 'Entregas de actividades',
                'ordering': ['-actualizado_en'],
                'constraints': [models.UniqueConstraint(fields=('actividad', 'estudiante'), name='uniq_entrega_actividad_por_estudiante')],
            },
        ),
    ]
