# Generated by Django 5.2.6 on 2026-04-06 22:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hechos', '0036_entrega_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregaactividad',
            name='archivo',
            field=models.FileField(blank=True, help_text='PDF, Word u otro formato permitido (opcional si ya escribiste respuesta).', null=True, upload_to='actividades/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'doc', 'docx', 'odt', 'txt', 'rtf', 'png', 'jpg', 'jpeg', 'webp'))], verbose_name='Archivo de evidencia'),
        ),
    ]
