# Generated by Django 5.2.6 on 2026-04-06 23:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_direccion'),
        ('hechos', '0037_entrega_archivo_actividades_dir'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoRecursoEscuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=220, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, help_text='Opcional. Indica para qué sirve el archivo.', verbose_name='Descripción')),
                ('archivo', models.FileField(upload_to='recursos_escuela/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'doc', 'docx', 'odt', 'txt', 'rtf', 'ppt', 'pptx', 'xls', 'xlsx', 'png', 'jpg', 'jpeg', 'webp', 'zip'))], verbose_name='Archivo')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_recurso', to='hechos.escuela')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_recurso_escuela', to='core.sede')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos_recurso_publicados', to='hechos.profesor')),
            ],
            options={
                'verbose_name': 'Archivo recurso de escuela',
                'verbose_name_plural': 'Archivos recurso por escuela',
                'ordering': ['-created_at'],
            },
        ),
    ]
