# Generated by Django 5.2.6 on 2026-04-17 22:47

import django.db.models.deletion
from django.db import migrations, models


def seed_capacidades_y_asignaciones(apps, schema_editor):
    CapacidadCoordinador = apps.get_model('hechos', 'CapacidadCoordinador')
    AdminEscuela = apps.get_model('hechos', 'AdminEscuela')
    AdminEscuelaCapacidad = apps.get_model('hechos', 'AdminEscuelaCapacidad')

    catalog = [
        (
            'academico',
            'Ámbito académico',
            'Estudiantes, matrículas, solicitudes, y tareas compartidas con el ámbito pedagógico.',
            10,
        ),
        (
            'pedagogico',
            'Ámbito pedagógico',
            'Profesores, estructura de ediciones, y tareas compartidas con el ámbito académico.',
            20,
        ),
        (
            'financiero',
            'Recursos y finanzas',
            'Ofrendas, recaudos ocasionales y presupuesto de eventos.',
            30,
        ),
        (
            'logistico',
            'Logística',
            'Salones y asignación por escuela.',
            40,
        ),
    ]
    codigo_to_cap = {}
    for codigo, nombre, descripcion, orden in catalog:
        obj, _ = CapacidadCoordinador.objects.update_or_create(
            codigo=codigo,
            defaults={
                'nombre': nombre,
                'descripcion': descripcion,
                'orden': orden,
            },
        )
        codigo_to_cap[codigo] = obj

    tipo_a_codigo = {
        'academico': 'academico',
        'pedagogico': 'pedagogico',
        'financiero': 'financiero',
        'logistico': 'logistico',
    }
    for ae in AdminEscuela.objects.all():
        codigo = tipo_a_codigo.get(ae.tipo_coordinador)
        if not codigo:
            continue
        cap = codigo_to_cap.get(codigo)
        if not cap:
            continue
        if AdminEscuelaCapacidad.objects.filter(admin_escuela_id=ae.pk, capacidad_id=cap.pk).exists():
            continue
        AdminEscuelaCapacidad.objects.create(
            admin_escuela_id=ae.pk,
            capacidad_id=cap.pk,
            orden=0,
        )


def unseed_capacidades(apps, schema_editor):
    AdminEscuelaCapacidad = apps.get_model('hechos', 'AdminEscuelaCapacidad')
    CapacidadCoordinador = apps.get_model('hechos', 'CapacidadCoordinador')
    AdminEscuelaCapacidad.objects.all().delete()
    CapacidadCoordinador.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('hechos', '0038_archivo_recurso_escuela'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacidadCoordinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=64, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Capacidad de coordinador',
                'verbose_name_plural': 'Capacidades de coordinador',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='AdminEscuelaCapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('admin_escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacidad_asignaciones', to='hechos.adminescuela')),
                ('capacidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='hechos.capacidadcoordinador')),
            ],
            options={
                'ordering': ['orden', 'capacidad__orden', 'id'],
                'constraints': [models.UniqueConstraint(fields=('admin_escuela', 'capacidad'), name='hechos_adminescuela_capacidad_unique')],
            },
        ),
        migrations.RunPython(seed_capacidades_y_asignaciones, unseed_capacidades),
    ]
