# Generated by Django 5.2.6 on 2026-04-17 22:51

from django.db import migrations, models


def marcar_capacidades_explicitas(apps, schema_editor):
    AdminEscuela = apps.get_model('hechos', 'AdminEscuela')
    AdminEscuela.objects.all().update(capacidades_explicitas=True)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hechos', '0039_capacidades_coordinador'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminescuela',
            name='capacidades_explicitas',
            field=models.BooleanField(default=False, help_text='Si es verdadero, los permisos en Hechos vienen solo de las capacidades asignadas (no del respaldo por tipo).'),
        ),
        migrations.RunPython(marcar_capacidades_explicitas, noop),
    ]
