# Generated by Django 5.2.6 on 2026-04-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hechos', '0041_textos_capacidad_sin_ambito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminescuela',
            name='tipo_coordinador',
            field=models.CharField(choices=[('sede', 'Coordinador de sede'), ('academico', 'Coordinador académico'), ('pedagogico', 'Coordinador pedagógico'), ('financiero', 'Coordinador financiero'), ('logistico', 'Coordinador logístico'), ('combinado', 'Coordinador (varias funciones)')], default='academico', max_length=20),
        ),
    ]
