# Generated by Django 5.2.6 on 2026-04-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hechos', '0055_nivel_programa_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escuelaprograma',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Texto libre sobre esta escuela en el programa.', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='nivelprograma',
            name='jerarquia',
            field=models.PositiveIntegerField(help_text='Número entero: 0 = Fundamentos, 1, 2, 3… ordenan el programa. Debe ser único por sede.', verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='nivelprograma',
            name='nombre',
            field=models.CharField(blank=True, help_text='Texto descriptivo (ej. Sanos y Libres). Se muestra junto al número como «Nivel N: nombre».', max_length=200, verbose_name='Nombre'),
        ),
    ]
