# Generated by Django 5.2.6 on 2026-04-18 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_user_tipo_documento'),
        ('hechos', '0056_nivel_programa_labels_nivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscuelaProgramaPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tiene_matricula', models.BooleanField(default=False, verbose_name='Tiene matrícula')),
                ('costo_matricula_cop', models.PositiveIntegerField(blank=True, null=True, verbose_name='Costo de matrícula (COP)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Escuela del programa (plantilla global)',
                'verbose_name_plural': 'Escuelas del programa (plantillas globales)',
                'ordering': ['nivel_plantilla__jerarquia', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='NivelProgramaPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jerarquia', models.PositiveIntegerField(help_text='0 = Fundamentos; 1, 2, 3… ordenan el programa. Único en todo el sistema.', verbose_name='Nivel')),
                ('nombre', models.CharField(blank=True, help_text='Texto descriptivo mostrado como «Nivel N: nombre».', max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del nivel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nivel del programa (plantilla global)',
                'verbose_name_plural': 'Niveles del programa (plantillas globales)',
                'ordering': ['jerarquia', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='escuelaprograma',
            name='plantilla',
            field=models.ForeignKey(blank=True, help_text='Si existe, esta fila proviene del catálogo compartido por todas las sedes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escuelas_en_sedes', to='hechos.escuelaprogramaplantilla', verbose_name='Plantilla global'),
        ),
        migrations.AddConstraint(
            model_name='nivelprogramaplantilla',
            constraint=models.UniqueConstraint(fields=('jerarquia',), name='uniq_hechos_nivel_programa_plantilla_jerarquia'),
        ),
        migrations.AddField(
            model_name='escuelaprogramaplantilla',
            name='nivel_plantilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escuelas', to='hechos.nivelprogramaplantilla', verbose_name='Nivel'),
        ),
        migrations.AddField(
            model_name='nivelprograma',
            name='plantilla',
            field=models.ForeignKey(blank=True, help_text='Si existe, esta fila proviene del catálogo compartido por todas las sedes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='niveles_en_sedes', to='hechos.nivelprogramaplantilla', verbose_name='Plantilla global'),
        ),
        migrations.AddConstraint(
            model_name='escuelaprogramaplantilla',
            constraint=models.UniqueConstraint(fields=('nivel_plantilla', 'nombre'), name='uniq_hechos_escuela_programa_plantilla_nivel_nombre'),
        ),
    ]
