# Generated by Django 5.2.6 on 2026-04-28 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_user_tipo_documento'),
        ('hechos', '0060_alinea_nuevo_lead_hechos_nombre_excel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaGrillaCelda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columna', models.PositiveIntegerField(help_text='1 = primer registro, 2 = segundo, etc.', verbose_name='Columna')),
                ('valor', models.CharField(choices=[('P', 'Asistió'), ('A', 'No asistió')], max_length=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grilla_asistencia_celdas', to='hechos.escuela')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grilla_asistencia_celdas', to='hechos.estudiante')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grilla_asistencia_registros', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grilla_asistencia_celdas', to='core.sede')),
            ],
            options={
                'verbose_name': 'Celda grilla asistencia',
                'verbose_name_plural': 'Celdas grilla asistencia',
                'ordering': ['columna', 'estudiante__user__last_name'],
                'unique_together': {('escuela', 'estudiante', 'columna')},
            },
        ),
        migrations.CreateModel(
            name='EscuelaGrillaAsistenciaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_columnas', models.PositiveIntegerField(default=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grilla_asistencia_configs', to='hechos.escuela')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grilla_asistencia_configs', to='core.sede')),
            ],
            options={
                'verbose_name': 'Configuración grilla de asistencia',
                'verbose_name_plural': 'Configuraciones grilla de asistencia',
                'constraints': [models.UniqueConstraint(fields=('escuela', 'sede'), name='uniq_grilla_asistencia_config_escuela_sede')],
            },
        ),
    ]
