# Generated by Django 5.2.6 on 2026-04-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hechos', '0062_grilla_asistencia_excel_apn'),
    ]

    operations = [
        migrations.AddField(
            model_name='edicioncurso',
            name='modalidad',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('hibrida', 'Híbrida')], default='presencial', help_text='Modalidad de la edición: presencial, virtual o híbrida.', max_length=16),
        ),
    ]
