# Generated by Django 5.2.6 on 2026-05-08 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hechos', '0064_grilla_notas_escuela'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escuela',
            options={'ordering': ['-anio', 'ciclo', 'nombre'], 'verbose_name': 'Escuela', 'verbose_name_plural': 'Escuelas'},
        ),
        migrations.AlterUniqueTogether(
            name='escuela',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='escuela',
            name='grupo',
        ),
    ]
