# Generated by Django 5.2.6 on 2026-07-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hechos', '0066_escuela_en_solicitudes_matriculas_clases_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('CE', 'Cédula de extranjería'), ('PAS', 'Pasaporte')], default='CC', max_length=3),
        ),
        migrations.AlterField(
            model_name='quejareclamo',
            name='tipo',
            field=models.CharField(choices=[('queja', 'Queja'), ('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia'), ('solicitud', 'Solicitud'), ('felicitacion', 'Felicitación')], default='queja', max_length=20),
        ),
    ]
