# Generated by Django 5.2.6 on 2026-07-26 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hechos', '0067_alter_estudiante_tipo_documento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notasgrillaestadofinal',
            name='certificado_activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notasgrillaestadofinal',
            name='certificado_emitido_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notasgrillaestadofinal',
            name='certificado_emitido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='cupo_maximo',
            field=models.PositiveIntegerField(default=30, help_text='Cupo máximo de estudiantes. 0 = indefinido (sin límite).'),
        ),
        migrations.AlterField(
            model_name='notificacionestudiante',
            name='tipo',
            field=models.CharField(choices=[('aprobacion', 'Aprobación'), ('rechazo', 'Rechazo'), ('info', 'Información'), ('certificado', 'Certificado')], default='info', max_length=20),
        ),
    ]
