# Generated by Django 5.2.6 on 2026-07-26 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hechos', '0068_notasgrillaestadofinal_certificado_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='iglesia',
        ),
    ]
