# Generated by Django 5.2.6 on 2026-07-26 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hechos', '0069_remove_estudiante_iglesia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='contacto_emergencia',
        ),
    ]
