# Generated by Django 5.2.6 on 2026-07-26 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hechos', '0070_remove_estudiante_contacto_emergencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='codigo_estudiante',
        ),
    ]
