# Generated by Django 5.2.6 on 2026-07-27 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hechos', '0071_remove_codigo_estudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='codigo_profesor',
        ),
    ]
