# Generated by Django 5.2.6 on 2026-07-27 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hechos', '0072_remove_codigo_profesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='experiencia_anos',
        ),
    ]
