# Generated by Django 5.2.6 on 2026-07-27 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hechos', '0073_remove_profesor_experiencia_anos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='biografia',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='especialidad',
        ),
    ]
