# Generated by Django 5.2.6 on 2026-07-27 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hechos', '0074_remove_profesor_especialidad_biografia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='notas_medicas',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='peticion_area',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='peticion_texto',
        ),
    ]
