# Generated by Django 5.2.6 on 2026-07-27 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_user_ubicacion_barrio_departamento_ciudad'),
        ('hechos', '0075_remove_estudiante_peticion_notas_medicas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('notas', models.CharField(blank=True, max_length=255, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_inventario', to='core.sede')),
            ],
            options={
                'verbose_name': 'Ítem de inventario',
                'verbose_name_plural': 'Ítems de inventario',
                'ordering': ['sede', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('sede', 'nombre'), name='uniq_hechos_item_inventario_nombre_por_sede')],
            },
        ),
    ]
